In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df =pd.read_csv ('IDS-DRSCountries_WLD_Country-SeriesMetadata.csv')
da =pd.read_csv('IDS-DRSCountries_WLD_CountryMetadata.csv')
db =pd.read_csv('IDS-DRSCountries_WLD_Data.csv')
dc =pd.read_csv('IDS-DRSCountries_WLD_Footnotes.csv')
dg =pd.read_csv('IDS-DRSCountries_WLD_SeriesMetadata.csv')

In [3]:
df.head()

,Type,Country Code,Series Code,Description
0,Country-Series,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan (AFG),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed and l...
2,Country-Series,Angola (AGO),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
3,Country-Series,Angola (AGO),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
4,Country-Series,Albania (ALB),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...

In [32]:
da.isnull().sum()

Code                                                   0
Long Name                                              0
Income Group                                          13
Region                                                13
Lending category                                      13
Other groups                                          93
Currency Unit                                         13
Latest population census                              15
Latest household survey                               16
Special Notes                                         94
National accounts base year                           13
National accounts reference year                     103
System of National Accounts                           14
SNA price valuation                                   13
Alternative conversion factor                         93
PPP survey years                                      14
Balance of Payments Manual in use                     15
External debt Reporting status                        14
System of trade                                       17
Government Accounting concept                         37
IMF data dissemination standard                       16
Source of most recent Income and expenditure data     17
Vital registration complete                           96
Latest agricultural census                            62
Latest industrial data                                46
Latest trade data                                     15
Latest water withdrawal data                          18
2-alpha code                                           0
WB-2 code                                              0
Table Name                                             0
Short Name                                             0
dtype: int64

In [30]:
db

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,1970,1971,1972,1973,...,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,...,NaN,17.9041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,...,NaN,17.9041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,...,NaN,73.0790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,...,NaN,73.0790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66104,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66105,Last Updated: 10/16/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
db.isnull().sum()

Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
                         ...
2023                     54492
2024                     54659
2025                     54939
2026                     55129
2027                     55272
Length: 64, dtype: int64

In [26]:
dc['Country Code'].isnull().sum()

0

In [7]:
dg.head()

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN